version: '2.1'

services:
  geode:
    image: docker.io/bitnami/geode:1
    ports:
      - 7070:7070
    environment:
      - GEODE_NODE_NAME=geode
      - GEODE_ADVERTISED_HOSTNAME=localhost
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: gfsh status locator --dir /bitnami/geode/data >/dev/null 2>&1 || exit 1
    volumes:
      - 'geode_data:/bitnami/geode'

volumes:
  geode_data:
    driver: local
